---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mx4dlv02mk3i/public_html/rockhounding.org
    - /bin/cp -R blog $DEPLOYPATH
    - /bin/cp -u /home/mx4dlv02mk3i/public_html/rockhounding.org/blog/index.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
